version: '3.4'
services:
  myapp:
    container_name: myapp
    image: my
    env_file: .env
    volumes:
      - bundle:/usr/local/bundle
      - $PWD:/var/www/app
    ports:
      - '3000:3000'
    links:
      - mydb
    networks: 
      - mynet
    command: rails s -b 0.0.0.0
    
  mydb:
    container_name: mydb
    image: library/mysql:5.6.22
    ports:
      - 3306:3306
    env_file: .env
    networks: 
      - mynet

  mynginx:
    container_name: mynginx
    image: nginx:alpine
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    links:
      - myapp
    networks: 
      - mynet

volumes:
  bundle:
    name: bundle
networks: 
  mynet:
  